Flask_Project/Blueprint_Project/BlueprintApp_TodoList/people/models.py
from BlueprintApp_TodoList.app import db

class Person(db.Model):
     __tablename__ = 'people' # name of table in db

     pid = db.Column(db.Integer, primary_key=True)
     name = db.Column(db.String, nullable=False)
     age = db.Column(db.Integer)
     job = db.Column(db.String)

     def __repr__(self):
        return f"<PERSON: {self.name}, Age: {self.age}>"
     
     def get_id(self):
        return self.pid

Flask_Project/Blueprint_Project/BlueprintApp_TodoList/people/__init__.py
# Making people a package

Flask_Project/Blueprint_Project/BlueprintApp_TodoList/people/routes.py
from flask import Flask,render_template, request,redirect,url_for,Blueprint

from BlueprintApp_TodoList.app import db
from BlueprintApp_TodoList.people.models import Person  # Todo is table name
#from BlueprintApp_TodoList.Todos.models import Todo

people = Blueprint('People', __name__, template_folder='templates') # Todos is blueprint name and 'todos' is blueprint variable used for route decorators and registering blueprint in main app

@people.route('/')
def index():
    people = Person.query.all()
    return render_template('people/index.html', people = people) # render template is not using blueprint name instead given dir path for index.html

@people.route('/create', methods=['GET','POST'])
def create():
    if request.method == 'GET':
        return render_template('people/create.html')
    elif request.method == 'POST':
        name = request.form.get('name')
        age = int(request.form.get('age'))
        job = request.form.get('job')

        job = job if job != "" else None

        person = Person(name = name, age = age, job = job )

        db.session.add(person)
        db.session.commit()

        return redirect(url_for('People.index')) # In redirect we will use Blueprint name "Todos.index"

Flask_Project/Blueprint_Project/BlueprintApp_TodoList/people/templates/people/create.html
{% extends "base.html" %}
{% block title %}Create People Page{% endblock %}

{% block content %}
<h1>Hello World, Hello World, This is Flask for People Create Page</h1>
<form action="{{ url_for('People.create') }}" method="POST">
    <input type="text" name="name" placeholder="Name" required="required"/>
    <input type="number" name="age" placeholder="Age" />
    <input type="text" name="job" placeholder="Job"/>
    <button type="submit" value="Create">Create</button>
</form>
{% endblock %}

Flask_Project/Blueprint_Project/BlueprintApp_TodoList/people/templates/people/index.html
{% extends "base.html" %}
{% block title %}Index People Page{% endblock %}

{% block content %}
<h1>Hello World, This is Flask for People Home Page</h1>
    <ul>
        {% for person in people %}
        <li>{{ person }}</li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('People.create') }}">Create People List</a>
{% endblock %}